### ISSUE TITLE
man moshkel daram 

### ISSUE THREAD

**Issue by ehswnmohseni** [Alireza0K/Naato#41]
code mano dozdidi

**Comment by Alireza0K** [comment]
Dear Mr. Ehsan Mohseni
Could you please elaborate on the issue you are facing? I am ready to assist you in any way I can.

**Comment by Alireza0K** [comment]
<img width="630" alt="Screenshot 2024-08-11 at 8 48 46 AM" src="https://github.com/user-attachments/assets/f41c433e-3ebf-4e54-bcc1-42542d91e7a5">

<img width="904" alt="Screenshot 2024-08-11 at 8 49 27 AM" src="https://github.com/user-attachments/assets/ccd52711-25b7-4f97-bc64-a42708c4386e">

As you can see I created this project myself, but I've added you as an owner [ehswnmohseni](https://github.com/ehswnmohseni)  to the repository with the username . You should be able to confirm this in the project's README.md file
